name: CI-CD

on:
  push:
    branches:
      - main

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Course Service
        run: |
          cd course-service
          mvn clean package -DskipTests

      - name: Build Enrollment Service
        run: |
          cd enrollment-service
          mvn clean package -DskipTests